### PR TITLE
FindDevice

### PR DESCRIPTION
**Pull request by cpvyb**
First simple implementation of FindDevice

### CODE REVIEW

**Comment by cpvyb** [comment]
I merged ahead your new code to test everything mixed. I guess I shouldn't. Next time I will make another branch for that.
You can do the merge of @cpvyb  FindDevice support and @cpvyb   Minor fix to FindDevice

**Comment by jareddlc** [comment]
Oh no it is fine, I was just curious how it happened. I'll test tomorrow :+1:

**Comment by jareddlc** [comment]
Finally tested it. Works great, I was wondering if I should emit some type of notification on the phone so it can be cleared by the phone as well, maybe as a second version, but for now I think its great! Do you mind doing a git squash so it can show up as 1 commit? I've used this tutorial before: http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html

Make sure to try it on a different branch so you wont break you current branch.

i think the command you want might be:

`$ git rebase -i HEAD~15` or `$ git rebase -i HEAD~14`

**Comment by cpvyb** [comment]
I will try to dump generated by Gerfit manager to stop the find device. 
I will generate another pull ready when ready.

I will do the squash today. Thanks for the help.

Carlos

**Pull request closed without merging**
