### PR TITLE
insertSleepData bug

### PR DESCRIPTION
**Pull request by jareddlc**
@winni159  please look at my current work. the bug is with insertSleepData

### CODE REVIEW

**Comment by winni159** [comment]
@jareddlc Hi, i'll look on it, but i have no problem with sleep data sync. Could you please specify the problem?
I see that you deleted [this row](https://github.com/jareddlc/OpenFit/pull/34/files#diff-e337625706d055a8ba3d80f5772c64dcR346), because it returns bad datetime (1.1.1970). I forgot to add these lines:
`timeStampEnd = source.readLong();`  and `source.writeLong(timeStampEnd);`  
to methods `public PedometerData(Parcel source) {}` and `public void writeToParcel(Parcel source, int flags) {}` in **PedometerData.java**

**Comment by jareddlc** [comment]
sorry, i posted this before sleeping, the code changes on this branch was to help me debug the issue, it wont be merged. However, if you take a look at master, ive merged your code.

**Comment by winni159** [comment]
I found where the problem is. I forgot to add SleepInfoList data:
`i.putParcelableArrayListExtra(OpenFitIntent.EXTRA_SLEEP_INFO_LIST, Fitness.getSleepInfoList());`
to ParcelableArrayList in `public void handleFitnessData(byte[] data) {}` [here](https://github.com/jareddlc/OpenFit/blob/sleepSyncBug/app/src/main/java/com/solderbyte/openfit/OpenFitService.java#L468). Can you add this 3 rows (2 which i mentioned above and 1 from this comment) to your code and test it? Thanks!

**Comment by jareddlc** [comment]
fixed and merge on diff branch

**Pull request closed without merging**
