### PR TITLE
Portuguese translation improvements

### PR DESCRIPTION
**Pull request by sampaiodiego**

### CODE REVIEW

**Comment by jareddlc** [comment]
awesome thanks @sampaiodiego for this, I am currently working on a 2.0.0 version and will be also needing more translations.

**Comment by sampaiodiego** [comment]
cool.. is it pushed somewhere? so I can start working on it already.

**Comment by jareddlc** [comment]
@sampaiodiego  not yet, It still in early development. It will be pushed to the 2.X.X branch

**Comment by sampaiodiego** [comment]
ok, looking forward to help on translations for 2.0 :grimacing: feel free to either close or merge if this PR (in case you cut out a new release fox 1.X :grin: )

**Pull request merged**
